### ISSUE TITLE
Great work and small issue

### ISSUE THREAD

**Issue by lufi1** [1996scarlet/faster-mobile-retinaface#3]
Hi Scarlet,

First of all, thanks for the great work. 
I tried your algorithm yesterday and it was super simple to use. 
I have some questions.

I can get the speed boost but I cannot get the same result on Wider face.
When I m trying to detect small and big faces at the same time, it doesn 't seem to work.

Do you have sample that we could test on in full HD ?

Thanks

**Comment by 1996scarlet** [comment]
lol,  you can change the scale in this line:
`fd = MxnetDetectionModel("weights/16and32", 0, scale=2.25, gpu=0, margin=0.15)`
eg: my webcam's output size is 640*480, if i want to make a full HD detection, just set the scale to `1080/480 = 2.25`
![22](https://user-images.githubusercontent.com/22913521/67109227-a09cd580-f202-11e9-905e-5b8a99d35db2.png)

I just test it with the model `16and32`, (in this picture) it can detect the small face and big face at the same time.
If you want to detect extremely small face at the same time, just use the model `8and16and32`, and **uncomment** the line #93 in `generate_anchor.py`.

**Comment by lufi1** [comment]
hi Scarlet and thanks for your answer.

Where can I find the 8and16and32 model ?
I m gonna try what you advized.
Thanks

**Comment by Tetsujinfr** [comment]
hi, the is no such 8and16and32 model in the weight directory. any chance wit that? thanks
really fast repo code, thanks
