### ISSUE TITLE
WARNING: erroneous pipeline: no element "v4l2src"

### ISSUE THREAD

**Issue by TorRient** [1996scarlet/faster-mobile-retinaface#4]
gst-launch-1.0 -q v4l2src device=/dev/video0 ! video/x-raw, width=640, height=480 ! videoconvert ! video/x-raw, format=BGR ! fdsink | python3 face_detector.py
WARNING: erroneous pipeline: no element "v4l2src"
[23:49:41] src/nnvm/legacy_json_util.cc:209: Loading symbol saved by previous version v1.5.0. Attempting to upgrade...
[23:49:41] src/nnvm/legacy_json_util.cc:217: Symbol successfully upgraded!

I'm try run code but it stop here. It no display camera
How to fix?
Thank you very much!!!

**Comment by 1996scarlet** [comment]
v4l2src is for usb camera only!!!
You can change the command to fit your input devices.
See the gstreamer doc for more [details](https://gstreamer.freedesktop.org/documentation/tools/gst-launch.html?gi-language=c).
Or you can use ffmpeg or others to gen the input raw image data.
